### ISSUE TITLE
男性器が覆われている部分について

### ISSUE THREAD

**Issue by asali6343** [w-e-w/sd-webui-nudenet-nsfw-censor#11]
男性器の覆われているcoveredの強度設定項目が欲しいです。

**Comment by w-e-w** [comment]
あー
無理です
このプロジェクトを使ったのニューラルネットワークは NudeNet https://github.com/notAI-tech/NudeNet
NudeNetのlabel `MALE_GENITALIA_COVERED` がありません
といえば `MALE_GENITALIA_COVERED` 一体何　`FEMALE_GENITALIA_COVERED` 区別がありますか？

**Comment by asali6343** [comment]
なるほどです。ご回答ありがとうございます。
ステイブルディフュージョンのバッチ処理で、こちらの機能を使わせていただいてるのですが、たまにモザイクが外れるので、精度をより上げるには男性器の覆われている強度の設定があればと思い、ご相談させていただきました。

**Comment by asali6343** [comment]
例えばモザイクが外れしまうパターンを画像学習させて、組み込むこととかは可能でしょうか？
もちろん必要であれば、こちらでも作業させていただきます。

**Comment by w-e-w** [comment]
NudeNet訓練に使用されたコードは公開されないようです

**Comment by asali6343** [comment]
> NudeNet訓練に使用されたコードは公開されないようです

ご丁寧に教えていただきありがとうございます。
現状これ以上の精度を高めるのは難しそうですね

**Comment by w-e-w** [comment]
>訓練に使用されたコードは公開されないようです

しょうがない～
そして私でこのextension使いません
自分でNudeNet訓練や似ているのネットワーク開発モチベーションが少ない

---

何を手動マスクモードがあります知ってますか
バッチ処理全自動が無理けどたまに数枚モザイクが外れるの場合は10分便利どう思う
![image](https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/assets/40751091/6602f3d4-6db4-4559-ae4b-b41df4b7b8bf)
