### ISSUE TITLE
[Feature request] Use only Canvas Draw mask in Extras

### ISSUE THREAD

**Issue by light-and-ray** [w-e-w/sd-webui-nudenet-nsfw-censor#4]
Hello! If I draw mask manually in Extras tab, and set checkbox "Canvas mask source"/"Draw mask", then the extension mixes my mask with detected mask. But in my case detected mask is completely wrong, and I want to use only my mask. Can you add checkbox or option for this behavior, please?

**Comment by w-e-w** [comment]
just don't check `Enable Nudenet Censor` checkbox, the check only applys to nudenet auto detection
if the mask is present then the censor filter will be applied

I probably should change the `Enable Nudenet Censor` I can see that my causes confusion
