### ISSUE TITLE
IDK what's wrong?? 

### ISSUE THREAD

**Issue by kyle215ps3** [w-e-w/sd-webui-nudenet-nsfw-censor#6]
I found out that sometimes SOME images will outright fail no matter what, even though I generated them directly from A1111 and they are the same kind of images I generated in a batch together.....
So somehow this extension is having problems with some images permanently, I even upscaled the image and then ran the censor and still fails.

*** Error completing request
*** Arguments: (1, <PIL.Image.Image image mode=RGB size=832x1024 at 0x27CC75547C0>, [<tempfile._TemporaryFileWrapper object at 0x0000027CC75559F0>, <tempfile._TemporaryFileWrapper object at 0x0000027CC7554F70>, <tempfile._TemporaryFileWrapper object at 0x0000027CC7554B80>, <tempfile._TemporaryFileWrapper object at 0x0000027CC7557FA0>, <tempfile._TemporaryFileWrapper object at 0x0000027CC7557880>, <tempfile._TemporaryFileWrapper object at 0x0000027CC75553C0>, <tempfile._TemporaryFileWrapper object at 0x0000027CC75574C0>], 'C:\\Users\\123ky\\Documents\\Automatic 1111\\FULL BACKUP\\DA Hentai\\AA Scheduled\\Tsunade Missionary\\11', 'C:\\Users\\123ky\\Documents\\Automatic 1111\\FULL BACKUP\\DA Hentai\\AA Scheduled\\Tsunade Missionary', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, True, False, 'Fill color', 10, 5, '#000000', 'Ellipse', 3, 0, 10, 0.5, 1, {'image': <PIL.Image.Image image mode=RGBA size=832x1024 at 0x27CC75543D0>, 'mask': <PIL.Image.Image image mode=RGB size=832x1024 at 0x27CC7557C40>}, ['Draw mask']) {}
    Traceback (most recent call last):
      File "C:\Users\123ky\Documents\Automatic 1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\123ky\Documents\Automatic 1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\123ky\Documents\Automatic 1111\stable-diffusion-webui\modules\postprocessing.py", line 59, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "C:\Users\123ky\Documents\Automatic 1111\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "C:\Users\123ky\Documents\Automatic 1111\stable-diffusion-webui\extensions\sd-webui-nudenet-nsfw-censor\scripts\nudenet_nsfw_censor_scripts\post_processing_script.py", line 150, in process
        nudenet_mask = pil_nude_detector.get_censor_mask(pp.image, nms_threshold, mask_shape, rectangle_round_radius, pil_nude_detector.thresholds, pil_nude_detector.expand_horizontal, pil_nude_detector.expand_vertical).convert('L')
    AttributeError: 'NoneType' object has no attribute 'convert'

**Comment by w-e-w** [comment]
update to the newest version this issue was fixed 2 days ago
https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/commit/ce3f654c90886e7b12dd5f43b853adf612fd5376#diff-560c405ad3ff630ea348a841aaf37579c4b9952da954545c270ad1317df5665dL150-R166

**Comment by flanteq** [comment]
Similar problem, but when using API.
Making the same changes in api.py (at line 54) solved the problem

**Comment by w-e-w** [comment]
> Similar problem, but when using API. Making the same changes in api.py (at line 54) solved the problem

lol, fixed 21 minutes before you posted https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/commit/a3d095dfea5d22b26f1a6c9034c1512a66599510
