### ISSUE TITLE
Detect whole image when generating img2img 

### ISSUE THREAD

**Issue by czzs** [w-e-w/sd-webui-nudenet-nsfw-censor#9]
I really like your extension with this level of customisation options! 

My only problem is that when I inpaint an image with _inpaint area = only masked_ option, the extension only scans the generated area instead of the whole image. Normally this should not be a huge problem, but it seams that this way Nudenet detects much more false positive areas than usually.

Eg. I inpainted an earring below an ear. The image contained the whole face and it was 100% SFW, but it only scanned the closeup ear, and the extension detected some adult content.

I tried to tweak with the options but I was not able to set up correctly. 

Is there a way to detect the whole image for NSFW content when inpainting?

Thanks in advance

**Comment by w-e-w** [comment]
thanks for noticing this issue

I have made a fix, but this fix also requires updates on the webui side so it won't work now
pending fix PR https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/pull/10

we have to waite after webui https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14657 has been merged over at webui
and that is only for the `dev` branch, it will take longer for the changes to be updated to master

**Comment by czzs** [comment]
Wow, thanks a lot! Waiting for the merge

**Comment by w-e-w** [comment]
- fix https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/pull/10 merged, but will only work if you are on webui dev branch 
> note this is not a recommendation for you to switch to dev as it is generally regarded as less stable
